/** @format */

import type { Metadata } from 'next';
import { Sora } from 'next/font/google';
import './globals.css';

const sora = Sora({
	display: 'swap',
	weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
	subsets: ['latin'],
});
export const metadata: Metadata = {
	title: 'Iceberg Digital',
	description: 'Generated by create next app',
	icons: '/favicon.png',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='pt-BR'>
			
			<body className={`${sora.className} antialiased`}>{children}</body>
		</html>
	);
}
